import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class ApiService {
  Gover_name:string[]=[]
  sec_gov_name:string[]=[]
  constructor() {
    let AllGover=[
              {name:"الدقهلية",
                  sections:[
                    {name:"السنبلاوين"},
                    {name:"تمي"},
                    {name:"اجا"},
                    {name:"طلخا "},
                    {name:"المنصوره"},
                    {name:"ميت غمر"},
                    {name:"المنزله"},
                    {name:"الجمالية"},
                    {name:"دكرنس"},
                    {name:"منية النصر"},
                    {name:"بني عبيد"},
                    {name:"شربين"},
                    {name:"المطرية"},
                    {name:"بلقاس"},
                    {name:"ميت سلسيل"},
                    {name:"محلة دمنه"},
                    {name:"نبروه"},
              ]},
              {name:"الجيزه",
                  sections:[
                    {name:"البدرشين"},
                    {name:"الصف"},
                    {name:"اطفيح"},
                    {name:"العياط"},
                    {name:"الواحات البحرية"},
                    {name:"منشاه القناطر"},
                    {name:"اوسيم"},
                    {name:"كرداسة"},
                    {name:"ابو النمرس"},
              ]},
              {name:"القليوبية",
                  sections:[
                    {name:"بنها"},
                    {name:"قليوب"},
                    {name:"القناطر الخيرية"},
                    {name:"الخانكة"},
                    {name:"كفر شكر"},
                    {name:"طوخ"},
                    {name:"شبين القناطر"},
                ]},
                {name:"الاسكندرية",
                  sections:[
                    {name:"برج العرب"},
                    {name:"الاسكندرية"},
                  ]},
                  {name:"البحيره",
                    sections:[
                      {name:"دمنهور"},
                      {name:"كفر الدوار"},
                      {name:"رشيد"},
                      {name:"ادكو"},
                      {name:"ابو المطامير"},
                      {name:"ابو حمص"},
                      {name:"الدلنجات"},
                      {name:"المحمودية"},
                      {name:"الرحمانية"},
                      {name:"ايتاي البارود"},
                      {name:"حوش عيسي"},
                      {name:"شبراخيت"},
                      {name:"كوم حماده"},
                      {name:"بدر"},
                      {name:"وادي النطرون"},
                  ]},
                  {name:"مرسي مطروح",
                  sections:[
                    {name:"مرسي مطروح"},
                    {name:"الحمام"},
                    {name:"العلمين"},
                    {name:"الضبعة"},
                    {name:"النجيلة"},
                    {name:"سيدي براني"},
                    {name:"السلوم"},
                    {name:"سيوه"},
                ]},
                {name:"دمياط",
                  sections:[
                    {name:"دمياط"},
                    {name:"فارسكور"},
                    {name:"كفر سعد"},
                    {name:"الزرقا"},
                    {name:"كفر البطيخ"},
                ]},
                {name:"كفر الشيخ",
                  sections:[
                    {name:"دسوق"},
                    {name:"كفر الشيخ"},
                    {name:"فوه"},
                    {name:"مطوبس"},
                    {name:"البرلس"},
                    {name:"الحامول"},
                    {name:"بيلا"},
                    {name:"الرياض"},
                    {name:"سيدي سالم"},
                    {name:"قلين"},
                  ]},
                  {name:"الغربية",
                    sections:[
                      {name:"طنطا"},
                      {name:"المحلة الكبري"},
                      {name:"كفر الزيات"},
                      {name:"زفتي"},
                      {name:"السنطة"},
                      {name:"قطور"},
                      {name:"بسيون"},
                      {name:"سمنود"},
                  ]},
                  {name:"المنوفية",
                    sections:[
                      {name:"شبين الكوم"},
                      {name:"السادات"},
                      {name:"منوف"},
                      {name:"اشمون"},
                      {name:"الباجور"},
                      {name:"قويسنا"},
                      {name:"بركة السبع"},
                      {name:"تلا"},
                      {name:"الشهداء"},
                  ]},
                  {name:"الشرقية",
                    sections:[
                      {name:"الزقازيق"},
                      {name:"منيا القمح"},
                      {name:"بلبيس"},
                      {name:"مشتول السوق"},
                      {name:"ابو حماد"},
                      {name:"هيهيا"},
                      {name:"ابو كبير"},
                      {name:"فاقوس"},
                      {name:"الابراهيمية"},
                      {name:"ديرب نجم"},
                      {name:"كفر صقر"},
                      {name:"اولاد صقر"},
                      {name:"الحسنية"},
                  ]},
                  {name:"الاسماعلية",
                    sections:[
                      {name:"الاسماعلية"},
                      {name:"فايد"},
                      {name:"القنطره شرق"},
                      {name:"القنطره غرب"},
                      {name:"التل الكبير"},
                      {name:"ابو صوير"},
                      {name:"القصاصين"},
                  ]},
                  {name:"شمال سيناء",
                    sections:[
                      {name:"العريش"},
                      {name:"الشيخ زويد"},
                      {name:"رفح"},
                      {name:"بئر العبد"},
                      {name:"الحسنة"},
                      {name:"نخل"},
                  ]},
                  {name:"بني سويف",
                    sections:[
                      {name:"بني سويف"},
                      {name:"الواسطي"},
                      {name:"ناصر"},
                      {name:"اهناسيا"},
                      {name:"بيا"},
                      {name:"سمسطا"},
                      {name:"الفشن"},
                  ]},
                  {name:"الفيوم",
                    sections:[
                      {name:"الفيوم"},
                      {name:"طامية"},
                      {name:"سنورس"},
                      {name:"اطسا"},
                      {name:"ابشواي"},
                      {name:"يوسف الصديق"},
                  ]},
                  {name:"المنيا",
                    sections:[
                      {name:"المنيا"},
                      {name:"العدوة"},
                      {name:"مغاغة"},
                      {name:"بني مزار"},
                      {name:"مطاي"},
                      {name:"سمالوط"},
                      {name:"ابو قرطاص"},
                      {name:"ملوي"},
                      {name:"دير مواس"},
                  ]},
                  {name:"اسيوط",
                    sections:[
                      {name:"اسيوط"},
                      {name:"ديوروط"},
                      {name:"منفلوط"},
                      {name:"القوصية"},
                      {name:"ابنوب"},
                      {name:"او تيج"},
                      {name:"الغنايم"},
                      {name:"ساحل سليم"},
                      {name:"البدراي"},
                      {name:"صدقا"},
                      {name:"الفتح"},
                  ]},
                  {name:"الوادي الجديد",
                    sections:[
                      {name:"الخارجة"},
                      {name:"باريس"},
                      {name:"الدخلة"},
                      {name:"الفرافره"},
                      {name:"بلاط"},
                  ]},
                  {name:"سوهاج",
                    sections:[
                      {name:"سوهاج"},
                      {name:"اخميم"},
                      {name:"البلينا"},
                      {name:"المراغة"},
                      {name:"المنشاة"},
                      {name:"دار السلام"},
                      {name:"جرجا"},
                      {name:"جهينة"},
                      {name:"ساقلته"},
                      {name:"طما"},
                      {name:"طهطا"},
                      {name:"العسيرات"},
                  ]},
                  {name:"الاقصر",
                    sections:[
                      {name:"الزينية"},
                      {name:"البياضية"},
                      {name:"القرنة"},
                      {name:"ارمنت"},
                      {name:"الطود"},
                      {name:"اسنا"},
                  ]},
                  {name:"اسوان",
                    sections:[
                      {name:"اسوان"},
                      {name:"دراو"},
                      {name:"كوم امبو"},
                      {name:"نصر النوبة"},
                      {name:"ادفو"},
                  ]},
                  {name:"قنا",
                    sections:[
                      {name:"قنا"},
                      {name:"ابو تشت"},
                      {name:"نجع حمادي"},
                      {name:"دشنا"},
                      {name:"الوقف"},
                      {name:"فقط"},
                      {name:"نقادة"},
                      {name:"قوص"},
                      {name:"فرشوط"},
                  ]},
                  {name:"القاهره",
                    sections:[
                      {name:"بولاق"},
                      {name:"جاردن سيتي"},
                      {name:"الزمالك"},
                      {name:"قصر النيل "},
                      {name:"مصر الجديده"},
                      {name:"النزهة"},
                      {name:"الوايلي"},
                      {name:"العباسية"},
                      {name:"البساتين"},
                      {name:"عين شمس"},
                      {name:"المرج"},
                      {name:"شبرا"},
                      {name:"الساحل"},
                      {name:"الزيتون"},
                      {name:"الزاويه الحمراء"},
                      {name:"الشرابية"},
                      {name:"روض الفرج"},
                      {name:"المطرية"},
                      {name:"المنيره"},
                      {name:"مصر القديمة"},
                      {name:"جزيره الروضة"},
                      {name:"دار السلام"},
                      {name:"المعادي"},
                      {name:"حلوان"},
                      {name:"المعصره"},
                      {name:"التبين"},
                      {name:"وسط القاهره"},
                      {name:"الموسكي"},
                      {name:"الخليفة"},
                      {name:"المقطم"},
                      {name:"باب الشعرية"},
                      {name:"السيده زينب"},
                      {name:"حي السلام"},
                      {name:"منشاه ناصر"},
                      {name:"القاهره"},
                      {name:"شبرا الخيمة"},
                      {name:"حدائق القبة"},
                      {name:"شبرا"},
                      {name:"السلام"},
                  ]},
                  {name:"البحر الاحمر",
                    sections:[
                      {name:"راس غارب"},
                      {name:"الغردقة"},
                      {name:"القصير"},
                      {name:"سفاجا"},
                      {name:"مرسي علم"},
                      {name:"شلاتين"},
                      {name:"حلايب"},
                  ]},
                  {name:"السويس",
                    sections:[
                      {name:"السويس"},
                      {name:"الاربعين"},
                      {name:"عتاقة"},
                      {name:"الجناين"},
                  ]},
                  {name:"بور سعيد",
                    sections:[
                      {name:"حي شرق"},
                      {name:"حي الجنوب"},
                      {name:"حي بور فؤاد"},
                      {name:"حي الضواحي"},
                      {name:"حي الزهور"},
                      {name:"حي العرب"},
                  ]},
                  {name:"جنوب سيناء",
                    sections:[
                      {name:"ابو رديس"},
                      {name:"ابو زنيمة"},
                      {name:"نويبع"},
                      {name:"طابا"},
                      {name:"راس سدر"},
                      {name:"دهب"},
                      {name:"شرم الشيخ"},
                      {name:"سانت كاترين"},
                      {name:"الطور"},
                  ]},
                      
    ]

   //gov name
    for (let sec_gov of AllGover){
      this.Gover_name.push(sec_gov.name)
    }
    //section name
    for(let sec_name of AllGover){
      sec_name.sections.map(ele =>{
        this.sec_gov_name.push(ele.name)
      })
    }
  
   }

 
}
